### ISSUE TITLE
Some links to the dataset have expired.

### ISSUE THREAD

**Issue by oli-21** [Kinpzz/SANet-TMM#2]
Thank you for sharing your great work.
I'd like to download the dataset referring to https://github.com/BCV-Uniandes/DMS according to README but the links below are expired.
REFERIT_SPLITS_URL="https://s3-sa-east-1.amazonaws.com/query-objseg/referit_splits.tar.bz2"
REFERIT_DATA_URL="http://www.eecs.berkeley.edu/~ronghang/projects/cvpr16_text_obj_retrieval/referitdata.tar.gz"
Could you share the dataset? Thank you very much.

**Comment by Kinpzz** [comment]
@oli-21 Sorry, the link was provided by its authors.  I don't have the copy of `referit` dataset currently. You might send a email to its authors.

**Comment by oli-21** [comment]
@Kinpzz Thank you very much for your quick reply.
I'd like to train and test using your method (SANet). Would you mind if you tell me how to do it without the referit dataset?

**Comment by Kinpzz** [comment]
@oli-21 The experiments are performed on each dataset individually. You can follow the instruction on README and just skip the referit dataset and choose other datasets like unc, unc+ and G-ref.

**Comment by oli-21** [comment]
@Kinpzz I understand. I'll try it.
Thank you for your kind explanation.
